apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    demo.last-refresh: '2026-06-09T12-42-14'
  name: "dev-cluster-199624066"
  namespace: argocd
spec:
  project: default
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  source:
    repoURL: 'https://mboersma.github.io/cluster-api-charts'
    chart: azure-aks-aso
    targetRevision: v0.4.2
    helm:
      valuesObject:
        clusterName: "dev-cluster-199624066"
        location: "swedencentral"
        subscriptionID: "cb5b077c-3ef5-4b2e-83e5-490cc5ca0e19"
        clientID: "370c507e-c87a-40ea-bb71-f6316a7abd24"
        tenantID: "16b3c013-d300-468d-ac64-7eda0820b6d3"
        authMode: "workloadidentity"
        kubernetesVersion: v1.34
        clusterNetwork: "overlay"
        withClusterClass: true
        withClusterTopology: true
        managedMachinePoolSpecs:
          pool0:
            count: 1
            enableAutoScaling: true
            enableEncryptionAtHost: false
            enableFIPS: false
            enableNodePublicIP: false
            enableUltraSSD: false
            maxCount: 3
            minCount: 1
            mode: System
            osSKU: AzureLinux
            vmSize: Standard_DS2_v2
            type: VirtualMachineScaleSets
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: -1
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 10m


